# -*- coding: utf-8 -*-
"""cie 1 30-07-24

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sC71_gVhIRKkg5CFPa9AkKNgxvhNIFQc
"""

import pandas as pd
data=pd.read_csv("/content/mtcars (2).csv")
data

import matplotlib.pyplot as plt
plt.scatter(data["wt"],data["mpg"])
plt.xlabel("weight")
plt.ylabel("mpg")
plt.title("Relation between weight of the car and mpg")
plt.show()

import matplotlib.pyplot as plt
plt.hist(data['mpg'],color='pink',edgecolor='black')
plt.xlabel("mpg")
plt.ylabel("Frequency")
plt.title("Histogram of mpg")
plt.show()

import matplotlib.pyplot as plt
tc=data.groupby('manufacturer').size().nlargest(5)
tc.plot(kind='bar',color='r')
plt.xlabel("model")
plt.ylabel("Frequency")
plt.title("frequency distribution")
plt.show()

import matplotlib.pyplot as plt
plt.boxplot(colomn='mpg',by='cyl')
plt.xlabel("cyl")
plt.ylabel("mpg")
plt.title("Boxplot of mpg")
plt.show()